// <auto-generated />
using System;
using DigitalisationManager.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DigitalisationManager.Data.Migrations
{
    [DbContext(typeof(DigitalisationManagerDbContext))]
    [Migration("20260420212924_AddArchiveLocationEntity")]
    partial class AddArchiveLocationEntity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DigitalisationManager.Data.Models.Entities.ArchiveLocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Room")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Shelf")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ArchiveLocations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 2, 13, 10, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Primary storage for municipal archive materials.",
                            Name = "Central Archive",
                            Room = "Room A",
                            Shelf = "Shelf 1"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 2, 13, 10, 5, 0, 0, DateTimeKind.Utc),
                            Description = "Storage area for photo and image materials.",
                            Name = "Photo Storage",
                            Room = "Room B",
                            Shelf = "Shelf 3"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 2, 13, 10, 10, 0, 0, DateTimeKind.Utc),
                            Description = "Restricted-access archival storage.",
                            Name = "Restricted Archive",
                            Room = "Room C",
                            Shelf = "Shelf 2"
                        });
                });

            modelBuilder.Entity("DigitalisationManager.Data.Models.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 2, 13, 9, 0, 0, 0, DateTimeKind.Utc),
                            Description = "General administrative and institutional documents.",
                            IsActive = true,
                            Name = "Administrative Records"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 2, 13, 9, 5, 0, 0, DateTimeKind.Utc),
                            Description = "Letters, notices, and official communication.",
                            IsActive = true,
                            Name = "Correspondence"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 2, 13, 9, 10, 0, 0, DateTimeKind.Utc),
                            Description = "Historical and documentary photographic materials.",
                            IsActive = true,
                            Name = "Photographic Materials"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 2, 13, 9, 15, 0, 0, DateTimeKind.Utc),
                            Description = "Registers, ledgers, and record books.",
                            IsActive = true,
                            Name = "Registers"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 2, 13, 9, 20, 0, 0, DateTimeKind.Utc),
                            Description = "Posters, brochures, invitations, and event materials.",
                            IsActive = true,
                            Name = "Exhibition Materials"
                        });
                });

            modelBuilder.Entity("DigitalisationManager.Data.Models.Entities.DigitalFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDownloadAllowed")
                        .HasColumnType("bit");

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<string>("OriginalChecksumSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("OriginalContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("OriginalRelativePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<long>("OriginalSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("OriginalStoredFileName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("PreviewContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PreviewRelativePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<long>("PreviewSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("PreviewStoredFileName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("OriginalChecksumSha256");

                    b.HasIndex("ItemId", "OriginalStoredFileName")
                        .IsUnique();

                    b.ToTable("DigitalFiles");
                });

            modelBuilder.Entity("DigitalisationManager.Data.Models.Entities.Fund", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("FundType")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Funds");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "AF-001",
                            CreatedAt = new DateTime(2026, 2, 13, 8, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Administrative documents from the municipal archive.",
                            FundType = 0,
                            Title = "Municipal Administration Archive"
                        },
                        new
                        {
                            Id = 2,
                            Code = "PF-001",
                            CreatedAt = new DateTime(2026, 2, 13, 8, 5, 0, 0, DateTimeKind.Utc),
                            Description = "Photographic materials from local history collections.",
                            FundType = 2,
                            Title = "Historical Photo Collection"
                        },
                        new
                        {
                            Id = 3,
                            Code = "AF-002",
                            CreatedAt = new DateTime(2026, 2, 13, 8, 10, 0, 0, DateTimeKind.Utc),
                            Description = "Administrative and educational archival records.",
                            FundType = 0,
                            Title = "School Documentation Archive"
                        },
                        new
                        {
                            Id = 4,
                            Code = "PF-002",
                            CreatedAt = new DateTime(2026, 2, 13, 8, 15, 0, 0, DateTimeKind.Utc),
                            Description = "Images from public events, festivals, and exhibitions.",
                            FundType = 2,
                            Title = "Cultural Events Photo Archive"
                        },
                        new
                        {
                            Id = 5,
                            Code = "AF-003",
                            CreatedAt = new DateTime(2026, 2, 13, 8, 20, 0, 0, DateTimeKind.Utc),
                            Description = "Letters and official communication records.",
                            FundType = 0,
                            Title = "Regional Correspondence Archive"
                        },
                        new
                        {
                            Id = 6,
                            Code = "PF-003",
                            CreatedAt = new DateTime(2026, 2, 13, 8, 25, 0, 0, DateTimeKind.Utc),
                            Description = "Museum photographs, exhibition visuals, and related materials.",
                            FundType = 2,
                            Title = "Museum Visual Collection"
                        });
                });

            modelBuilder.Entity("DigitalisationManager.Data.Models.Entities.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ArchiveLocationId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("DocumentDateText")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("FundId")
                        .HasColumnType("int");

                    b.Property<string>("InventoryNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ArchiveLocationId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("FundId", "InventoryNumber")
                        .IsUnique();

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 2, 14, 8, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Municipal council annual report",
                            DocumentDateText = "1948",
                            FundId = 1,
                            InventoryNumber = "INV-001",
                            Status = 0
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 2, 14, 8, 5, 0, 0, DateTimeKind.Utc),
                            Description = "Official correspondence with regional authorities",
                            DocumentDateText = "1951",
                            FundId = 1,
                            InventoryNumber = "INV-002",
                            Status = 0
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2026, 2, 14, 8, 10, 0, 0, DateTimeKind.Utc),
                            Description = "Registry of municipal decisions",
                            DocumentDateText = "1955",
                            FundId = 1,
                            InventoryNumber = "INV-003",
                            Status = 1
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 2, 14, 8, 15, 0, 0, DateTimeKind.Utc),
                            Description = "Administrative budget summary",
                            DocumentDateText = "1960",
                            FundId = 1,
                            InventoryNumber = "INV-004",
                            Status = 0
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2026, 2, 14, 8, 20, 0, 0, DateTimeKind.Utc),
                            Description = "City square historical photograph",
                            DocumentDateText = "1932",
                            FundId = 2,
                            InventoryNumber = "INV-005",
                            Status = 2
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2026, 2, 14, 8, 25, 0, 0, DateTimeKind.Utc),
                            Description = "Street life photography collection",
                            DocumentDateText = "1940",
                            FundId = 2,
                            InventoryNumber = "INV-006",
                            Status = 0
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2026, 2, 14, 8, 30, 0, 0, DateTimeKind.Utc),
                            Description = "Exhibition invitation photograph set",
                            DocumentDateText = "1957",
                            FundId = 2,
                            InventoryNumber = "INV-007",
                            Status = 1
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2026, 2, 14, 8, 35, 0, 0, DateTimeKind.Utc),
                            Description = "Railway station archival photo",
                            DocumentDateText = "1964",
                            FundId = 2,
                            InventoryNumber = "INV-008",
                            Status = 0
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 2, 14, 8, 40, 0, 0, DateTimeKind.Utc),
                            Description = "School administration annual register",
                            DocumentDateText = "1971",
                            FundId = 3,
                            InventoryNumber = "INV-009",
                            Status = 0
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2026, 2, 14, 8, 45, 0, 0, DateTimeKind.Utc),
                            Description = "Student attendance register",
                            DocumentDateText = "1972",
                            FundId = 3,
                            InventoryNumber = "INV-010",
                            Status = 1
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 2, 14, 8, 50, 0, 0, DateTimeKind.Utc),
                            Description = "Correspondence between schools",
                            DocumentDateText = "1974",
                            FundId = 3,
                            InventoryNumber = "INV-011",
                            Status = 0
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 2, 14, 8, 55, 0, 0, DateTimeKind.Utc),
                            Description = "Regional education report",
                            DocumentDateText = "1976",
                            FundId = 3,
                            InventoryNumber = "INV-012",
                            Status = 0
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2026, 2, 14, 9, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Festival opening ceremony photo",
                            DocumentDateText = "1981",
                            FundId = 4,
                            InventoryNumber = "INV-013",
                            Status = 2
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2026, 2, 14, 9, 5, 0, 0, DateTimeKind.Utc),
                            Description = "Exhibition poster materials",
                            DocumentDateText = "1983",
                            FundId = 4,
                            InventoryNumber = "INV-014",
                            Status = 0
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2026, 2, 14, 9, 10, 0, 0, DateTimeKind.Utc),
                            Description = "Community event photography",
                            DocumentDateText = "1986",
                            FundId = 4,
                            InventoryNumber = "INV-015",
                            Status = 1
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2026, 2, 14, 9, 15, 0, 0, DateTimeKind.Utc),
                            Description = "Cultural program leaflet",
                            DocumentDateText = "1988",
                            FundId = 4,
                            InventoryNumber = "INV-016",
                            Status = 0
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 2, 14, 9, 20, 0, 0, DateTimeKind.Utc),
                            Description = "Official regional correspondence file",
                            DocumentDateText = "1990",
                            FundId = 5,
                            InventoryNumber = "INV-017",
                            Status = 0
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 2, 14, 9, 25, 0, 0, DateTimeKind.Utc),
                            Description = "Interdepartmental letter archive",
                            DocumentDateText = "1991",
                            FundId = 5,
                            InventoryNumber = "INV-018",
                            Status = 1
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 2, 14, 9, 30, 0, 0, DateTimeKind.Utc),
                            Description = "Regional administrative notice",
                            DocumentDateText = "1993",
                            FundId = 5,
                            InventoryNumber = "INV-019",
                            Status = 0
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2026, 2, 14, 9, 35, 0, 0, DateTimeKind.Utc),
                            Description = "Correspondence register ledger",
                            DocumentDateText = "1995",
                            FundId = 5,
                            InventoryNumber = "INV-020",
                            Status = 0
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2026, 2, 14, 9, 40, 0, 0, DateTimeKind.Utc),
                            Description = "Museum interior visual archive",
                            DocumentDateText = "2001",
                            FundId = 6,
                            InventoryNumber = "INV-021",
                            Status = 2
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2026, 2, 14, 9, 45, 0, 0, DateTimeKind.Utc),
                            Description = "Artifact display photography",
                            DocumentDateText = "2004",
                            FundId = 6,
                            InventoryNumber = "INV-022",
                            Status = 0
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2026, 2, 14, 9, 50, 0, 0, DateTimeKind.Utc),
                            Description = "Exhibition brochure archive",
                            DocumentDateText = "2008",
                            FundId = 6,
                            InventoryNumber = "INV-023",
                            Status = 1
                        },
                        new
                        {
                            Id = 24,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2026, 2, 14, 9, 55, 0, 0, DateTimeKind.Utc),
                            Description = "Temporary exhibition visuals",
                            DocumentDateText = "2012",
                            FundId = 6,
                            InventoryNumber = "INV-024",
                            Status = 0
                        });
                });

            modelBuilder.Entity("DigitalisationManager.Data.Models.Entities.ItemHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ItemId", "CreatedAt");

                    b.ToTable("ItemHistories");
                });

            modelBuilder.Entity("DigitalisationManager.Data.Models.Identity.ApplicationRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Label")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            ConcurrencyStamp = "44444444-4444-4444-4444-444444444444",
                            Label = "Administrator",
                            Name = "Administrator",
                            NormalizedName = "ADMINISTRATOR"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            ConcurrencyStamp = "55555555-5555-5555-5555-555555555555",
                            Label = "User",
                            Name = "User",
                            NormalizedName = "USER"
                        },
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-999999999999"),
                            ConcurrencyStamp = "88888888-8888-8888-8888-888888888888",
                            Label = "Manager",
                            Name = "Manager",
                            NormalizedName = "MANAGER"
                        });
                });

            modelBuilder.Entity("DigitalisationManager.Data.Models.Identity.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "77777777-7777-7777-7777-777777777777",
                            Email = "admin@admin.local",
                            EmailConfirmed = true,
                            FirstName = "System",
                            LastName = "Administrator",
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@ADMIN.LOCAL",
                            NormalizedUserName = "ADMIN@ADMIN.LOCAL",
                            PasswordHash = "AQAAAAIAAYagAAAAEJppDSosLe9PSUf4y/CwEcXtNPrwJxBFBtvTU7MqRSMVnEh4AjnV/UmXREB1jwelWA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "66666666-6666-6666-6666-666666666666",
                            TwoFactorEnabled = false,
                            UserName = "admin@admin.local"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "manager-concurrency-stamp",
                            Email = "manager@manager.com",
                            EmailConfirmed = true,
                            FirstName = "Archive",
                            LastName = "Manager",
                            LockoutEnabled = false,
                            NormalizedEmail = "MANAGER@MANAGER.COM",
                            NormalizedUserName = "MANAGER@MANAGER.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAENIhe5FuMqz0sI+E1B6wCCCwsHQdHjtB3Bzd+6z4sSq1JturIcp3a6rUOMExG0IKtQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "manager-security-stamp",
                            TwoFactorEnabled = false,
                            UserName = "manager@manager.com"
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "user-concurrency-stamp",
                            Email = "user@user.com",
                            EmailConfirmed = true,
                            FirstName = "Archive",
                            LastName = "User",
                            LockoutEnabled = false,
                            NormalizedEmail = "USER@USER.COM",
                            NormalizedUserName = "USER@USER.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEFxFJP1QxDchH+Mj3Zuae8NAlh+3k54Lktrxp2gRRl7EXW44v32IdlDWwsj4Gm+qJw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "user-security-stamp",
                            TwoFactorEnabled = false,
                            UserName = "user@user.com"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = new Guid("33333333-3333-3333-3333-333333333333"),
                            RoleId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            UserId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            RoleId = new Guid("99999999-9999-9999-9999-999999999999")
                        },
                        new
                        {
                            UserId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            RoleId = new Guid("22222222-2222-2222-2222-222222222222")
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("DigitalisationManager.Data.Models.Entities.DigitalFile", b =>
                {
                    b.HasOne("DigitalisationManager.Data.Models.Entities.Item", "Item")
                        .WithMany("DigitalFiles")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Item");
                });

            modelBuilder.Entity("DigitalisationManager.Data.Models.Entities.Item", b =>
                {
                    b.HasOne("DigitalisationManager.Data.Models.Entities.ArchiveLocation", "ArchiveLocation")
                        .WithMany("Items")
                        .HasForeignKey("ArchiveLocationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DigitalisationManager.Data.Models.Entities.Category", "Category")
                        .WithMany("Items")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DigitalisationManager.Data.Models.Entities.Fund", "Fund")
                        .WithMany("Items")
                        .HasForeignKey("FundId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ArchiveLocation");

                    b.Navigation("Category");

                    b.Navigation("Fund");
                });

            modelBuilder.Entity("DigitalisationManager.Data.Models.Entities.ItemHistory", b =>
                {
                    b.HasOne("DigitalisationManager.Data.Models.Entities.Item", "Item")
                        .WithMany("ItemHistories")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("DigitalisationManager.Data.Models.Identity.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("DigitalisationManager.Data.Models.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("DigitalisationManager.Data.Models.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("DigitalisationManager.Data.Models.Identity.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DigitalisationManager.Data.Models.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("DigitalisationManager.Data.Models.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DigitalisationManager.Data.Models.Entities.ArchiveLocation", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("DigitalisationManager.Data.Models.Entities.Category", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("DigitalisationManager.Data.Models.Entities.Fund", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("DigitalisationManager.Data.Models.Entities.Item", b =>
                {
                    b.Navigation("DigitalFiles");

                    b.Navigation("ItemHistories");
                });
#pragma warning restore 612, 618
        }
    }
}
